[project]
name = "sys-bench"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.6",
    "speedtest-cli>=2.1.3",
    "tabulate>=0.9.0",
    "torch>=2.10.0",
]
